In [1]:
import pandas as pd

In [7]:
MAS_Main_Data_CS = pd.read_stata('MAS_Main Data_CS.dta')
MAS_Main_Data_Panel = pd.read_stata('MAS_Main Data_Panel.dta')
MAS_Original_Data_CS = pd.read_stata('MAS_Original Data_CS.dta')
MAS_Original_Data_Panel = pd.read_stata('MAS_Original Data_Panel.dta')

In [10]:
MAS_Main_Data_Panel.head()

,acr,id,obsid,confid,dyadid,dyadperiod,side_a,side_b,location,year,...,yearnohealthcount,yearexclusivehealthcount,exclude,id_use,yearpubeducountsec,yearpubeducountnonsec,countnonsec,countsec,yearpubhealthcountsec,yearpubhealthcountnonsec
0,NTH,NTH-1945,EACD.2.2-19,1050,1050-1,1,Netherlands,Indonesian Peoples Army,Indonesia,1945.0,...,1.0,0.0,NaN,Indonesian Peoples ArmyNetherlandsIndonesia1945,NaN,0.0,1.0,NaN,NaN,0.0
1,BOL,BOL-1946,EACD.2.2-1,1010.1,1010.1-1,1,Bolivia,Popular Revolutionary Movement,Bolivia,1946.0,...,3.0,7.0,0.0,Popular Revolutionary MovementBoliviaBolivia1946,NaN,NaN,NaN,NaN,NaN,NaN
2,NTH,NTH-1946,EACD.2.2-19,1050,1050-1,1,Netherlands,Indonesian Peoples Army,Indonesia,1946.0,...,3.0,7.0,NaN,Indonesian Peoples ArmyNetherlandsIndonesia1946,NaN,0.0,6.0,NaN,NaN,0.0
3,RUS,RUS-1946,EACD.2.2-55,1120,1120-1,1,Soviet Union,LTS[p]A,Soviet Union,1946.0,...,3.0,7.0,0.0,LTS[p]ASoviet UnionSoviet Union1946,NaN,NaN,NaN,NaN,NaN,NaN
4,RUS,RUS-1946,EACD.2.2-64,1140,1140-1,1,Soviet Union,UPA,Soviet Union,1946.0,...,3.0,7.0,0.0,UPASoviet UnionSoviet Union1946,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
MAS_Main_Data_Panel[['id_use','yearpubhealthcountsec','yearpubhealthcountnonsec','yearpubeducountsec','yearpubeducountnonsec']]

,id_use,yearpubhealthcountsec,yearpubhealthcountnonsec,yearpubeducountsec,yearpubeducountnonsec
0,Indonesian Peoples ArmyNetherlandsIndonesia1945,NaN,0.0,NaN,0.0
1,Popular Revolutionary MovementBoliviaBolivia1946,NaN,NaN,NaN,NaN
2,Indonesian Peoples ArmyNetherlandsIndonesia1946,NaN,0.0,NaN,0.0
3,LTS[p]ASoviet UnionSoviet Union1946,NaN,NaN,NaN,NaN
4,UPASoviet UnionSoviet Union1946,NaN,NaN,NaN,NaN
5,Viet Nam Doc Dong Min HoiFranceVietnam1946,NaN,0.0,NaN,0.0
6,LNPASoviet UnionSoviet Union1946,NaN,NaN,NaN,NaN
7,IZL [Etzel]United KingdomIsrael1946,NaN,NaN,NaN,NaN
8,Lao IssaraFranceLaos1946,NaN,NaN,NaN,NaN
9,HukPhilippinesPhilippines1946,NaN,0.0,NaN,0.0
10,Forest BrothersSoviet UnionSoviet Union1946,NaN,NaN,NaN,NaN
11,Republic of Kurdistan/KDPIIranIran1946,0.0,NaN,0.0,NaN
12,Khmer IssarakFranceCambodia1946,NaN,0.0,NaN,0.0
13,Peoples Liberation ArmyChinaChina1946,NaN,0.0,NaN,0.0
14,BDPSSoviet UnionSoviet Union1946,NaN,NaN,NaN,NaN
15,DSEGreeceGreece1946,NaN,0.0,NaN,0.0
16,MDRMFranceMadagascar1947,NaN,0.0,NaN,0.0
17,"Opposition coalition [Febreristas, Liberals an...",NaN,0.0,NaN,0.0
18,CPIHyderabadHyderabad1947,NaN,NaN,NaN,NaN
19,UPASoviet UnionSoviet Union1947,NaN,NaN,NaN,NaN
20,HukPhilippinesPhilippines1947,NaN,0.0,NaN,0.0
21,Indonesian Peoples ArmyNetherlandsIndonesia1947,NaN,0.0,NaN,0.0
22,Lao IssaraFranceLaos1947,NaN,NaN,NaN,NaN
23,LNPASoviet UnionSoviet Union1947,NaN,NaN,NaN,NaN
24,Forest BrothersSoviet UnionSoviet Union1947,NaN,NaN,NaN,NaN
25,Peoples Liberation ArmyChinaChina1947,NaN,0.0,NaN,0.0
26,BDPSSoviet UnionSoviet Union1947,NaN,NaN,NaN,NaN
27,Khmer IssarakFranceCambodia1947,NaN,0.0,NaN,0.0
28,LTS[p]ASoviet UnionSoviet Union1947,NaN,NaN,NaN,NaN
29,DSEGreeceGreece1947,NaN,0.0,NaN,0.0
...,...,...,...,...,...
2301,BDSF/NDFBIndiaIndia2003,NaN,NaN,NaN,NaN
2302,GAMIndonesiaIndonesia2003,3.0,NaN,4.0,NaN
2303,MCCIndiaIndia2003,NaN,NaN,NaN,NaN
2304,NPAPhilippinesPhilippines2003,NaN,1.0,NaN,0.0
2305,Kashmir InsurgentsIndiaIndia2003,NaN,NaN,NaN,NaN
2306,PFLP-GCIsraelIsrael2003,NaN,NaN,NaN,NaN
2307,UNLFIndiaIndia2003,NaN,NaN,NaN,NaN
2308,LURDLiberiaLiberia2003,NaN,NaN,NaN,NaN
2309,KNUBurmaBurma2003,3.0,NaN,4.0,NaN
2310,LRAUgandaUganda2003,NaN,NaN,NaN,NaN
2311,PFLPIsraelIsrael2003,NaN,NaN,NaN,NaN
2312,MILFPhilippinesPhilippines2003,NaN,NaN,NaN,NaN
2313,ELNColombiaColombia2003,NaN,1.0,NaN,0.0
2314,TalibanAfghanistanAfghanistan2003,NaN,NaN,NaN,NaN
2315,SSABurmaBurma2003,3.0,NaN,4.0,NaN
2316,Palipehutu-FNLBurundiBurundi2003,NaN,NaN,NaN,NaN
2317,LTTESri LankaSri Lanka2003,3.0,NaN,4.0,NaN
2318,ONLFEthiopiaEthiopia2003,NaN,NaN,NaN,NaN
2319,NLFTIndiaIndia2003,NaN,NaN,NaN,NaN
2320,ADFUgandaUganda2003,NaN,NaN,NaN,NaN
2321,Naxalites/PWGIndiaIndia2003,NaN,NaN,NaN,NaN
2322,CPN-M/UPFNepalNepal2003,NaN,1.0,NaN,0.0
2323,GIAAlgeriaAlgeria2003,NaN,NaN,NaN,NaN
2324,SPLMSudanSudan2003,NaN,1.0,NaN,0.0
2325,BLTFIndiaIndia2003,NaN,NaN,NaN,NaN
2326,FARCColombiaColombia2003,NaN,1.0,NaN,0.0
2327,AMBIsraelIsrael2003,NaN,NaN,NaN,NaN
2328,UFLA FactionIndiaIndia2003,3.0,NaN,4.0,NaN
2329,ATTFIndiaIndia2003,NaN,NaN,NaN,NaN
2330,FLECAngolaAngola2003,NaN,NaN,NaN,NaN

In [8]:
for i in MAS_Main_Data_Panel.columns:
    print(i)

acr
id
obsid
confid
dyadid
dyadperiod
side_a
side_b
location
year
pg
sec2
communist
ethnonsec
dur
l1imr
l1gdppc_log
l1democracy
l1totalpop_log
totalpop_change_log
lmtnest
rebord
rs1
rs2
rs3
rs4
nonmilex
logrs
groups2
bd_best_low_log
preconflict_edu
preconflict_health
regionnum1
regionnum2
regionnum3
regionnum4
dec40
dec50
dec60
dec70
dec80
dec90
terrcontrol
locnum1
locnum2
locnum3
locnum4
locnum5
locnum6
locnum7
locnum8
locnum9
locnum10
locnum11
locnum12
locnum13
locnum14
locnum15
locnum16
locnum17
locnum18
locnum19
locnum20
locnum21
locnum22
locnum23
locnum24
locnum25
locnum26
locnum27
locnum28
locnum29
locnum30
locnum31
locnum32
locnum33
locnum34
locnum35
locnum36
locnum37
locnum38
locnum39
locnum40
locnum41
locnum42
locnum43
locnum44
locnum45
locnum46
locnum47
locnum48
locnum49
locnum50
locnum51
locnum52
locnum53
locnum54
locnum55
locnum56
locnum57
locnum58
locnum59
locnum60
locnum61
locnum62
locnum63
locnum64
locnum65
locnum66
locnum67
locnum68
locnum69
locnum70
locnum71
locnum72
locnum73
locnum74
locnum75
locnum76
locnum77
locnum78
locnum79
locnum80
locnum81
locnum82
locnum83
locnum84
locnum85
locnum86
locnum87
locnum88
locnum89
locnum90
locnum91
locnum92
locnum93
locnum94
locnum95
locnum96
locnum97
locnum98
locnum99
locnum100
locnum101
locnum102
locnum103
locnum104
locnum105
locnum106
locnum107
locnum108
locnum109
pg_zero
pg_one
pg_alt
pgb
pg_ord
seccol
secbroad3
secbroad4
yearmin
yearpubeducount
yearcount
yearpubhealthcount
eduannual
healthannual
yearnoeducount
yearexclusiveeducount
yearnohealthcount
yearexclusivehealthcount
exclude
id_use
yearpubeducountsec
yearpubeducountnonsec
countnonsec
countsec
yearpubhealthcountsec
yearpubhealthcountnonsec

In [ ]:


"""
****FIGURES A.4 and A.5: Education or Health Care Provision by Goals, Overtime (Panel)***
label var yearpubhealthcountnonsec"Inclusive Services, Non-Secessionist"
label var yearpubhealthcountsec "Inclusive Services, Secessionist"
label var countnonsec "Non-Secessionist"
label var yearpubeducountnonsec "Inclusive Services, Non-Secessionist"
label var countsec "Secessionist"
label var yearpubeducountsec "Inclusive Services, Secessionist"
"""